#include "MODE.h"


uint32_t MODE::CheckSpentTime(){
  return spentTime;
}
void MODE::mainloop(){
  //前回実行時からの経過時間を計算
  deltaTime = millis() - cycleTime;
  //経過時間を計算
  spentTime = millis() - startTime;


  if(deltaTime >= TaskSpan){
    if(!_InitCondition){//未初期化時実行
//      Serial.println("Init");
      InitFunction();
    }else if(_DeinitCondition){//修了処理時実行
//      Serial.println("Deinit");
      DeinitFunction();
    }else{
//      Serial.println("main()");
      main();
    }
    //cycleTimeリセット
    cycleTime = millis();
  }
}
void MODE::InitActive(){
  startTime = millis();
  _InitCondition=true;
}
void MODE::DeinitActive(){
  startTime = millis();
  _DeinitCondition=true;
}
void MODE::InitFunction(){
  //
  motor->move(10);
  led->flash(_value);
//  led->counter(_InitCounter);
//  _InitCounter++;
  if(_InitMode==0){
    if(spentTime>0)motor->changeFreq(8);
    if(spentTime>100)motor->changeFreq(12);
    if(spentTime>200)motor->changeFreq(11);
    if(spentTime>300)motor->changeFreq(10);
    if(spentTime>400)motor->changeFreq(9);
    if(spentTime>500)motor->changeFreq(8);
    if(spentTime>600){
      motor->move(0);
      InitActive();;
    }
  }

  if(_InitMode==1){
    if(spentTime>0)motor->changeFreq(8);
    if(spentTime>100)motor->changeFreq(9);
    if(spentTime>200)motor->changeFreq(10);
    if(spentTime>300)motor->changeFreq(11);
    if(spentTime>400)motor->changeFreq(12);
    if(spentTime>500)motor->changeFreq(8);
    if(spentTime>600){
      motor->move(0);
      InitActive();;
    }
  }
  if(_InitMode==2){
    if(spentTime>0)motor->changeFreq(8);
    if(spentTime>100)motor->changeFreq(12);
    if(spentTime>200)motor->changeFreq(9);
    if(spentTime>300)motor->changeFreq(12);
    if(spentTime>400)motor->changeFreq(9);
    if(spentTime>500)motor->changeFreq(12);
    if(spentTime>600)motor->changeFreq(9);
    if(spentTime>700)motor->changeFreq(12);
    if(spentTime>800)motor->changeFreq(8);
    if(spentTime>900){
      motor->move(0);
      InitActive();;
    }
  }
  if(_InitMode==3){
    if(spentTime>0)motor->changeFreq(8);
    if(spentTime>100)motor->changeFreq(9);
    if(spentTime>200){
      motor->changeFreq(10);
    }
    if(spentTime>300){
      motor->move(0);
    }
    if(spentTime>400){
      motor->move(10);
      motor->changeFreq(11);
    }
    if(spentTime>500)motor->changeFreq(12);
    if(spentTime>600)motor->changeFreq(13);
    if(spentTime>700){
      motor->move(0);
      InitActive();;
    }
  }
  if(_InitMode==4){
    if(spentTime>0){
      motor->changeFreq(12);
    }
    if(spentTime>100)motor->move(0);
    if(spentTime>200){
      motor->move(10);
      motor->changeFreq(10);
    }
    if(spentTime>300){
      motor->changeFreq(11);
    }
    if(spentTime>400){
      motor->changeFreq(8);
    }
    if(spentTime>500){
      motor->move(0);
      InitActive();;
    }
  }
  if(_InitMode==5){
    if(spentTime>0)motor->changeFreq(12);
    if(spentTime>100)motor->changeFreq(8);
    if(spentTime>200)motor->changeFreq(12);
    if(spentTime>300)motor->changeFreq(8);
    if(spentTime>400)motor->changeFreq(12);
    if(spentTime>500)motor->changeFreq(8);
    if(spentTime>600){
      motor->move(0);
      InitActive();;
    }
  }
  if(_InitMode==6){
    if(spentTime>0)motor->changeFreq(12);
    if(spentTime>100)motor->changeFreq(13);
    if(spentTime>200)motor->changeFreq(11);
    if(spentTime>300)motor->changeFreq(10);
    if(spentTime>400)motor->changeFreq(9);
    if(spentTime>500)motor->changeFreq(8);
    if(spentTime>600){
      motor->move(0);
      InitActive();;
    }
  }
  if(_InitMode==7){
    if(spentTime>0)motor->changeFreq(7);
    if(spentTime>100)motor->changeFreq(9);
    if(spentTime>200)motor->changeFreq(8);
    if(spentTime>300)motor->changeFreq(10);
    if(spentTime>400)motor->changeFreq(11);
    if(spentTime>500)motor->changeFreq(12);
    if(spentTime>600)motor->changeFreq(11);
    if(spentTime>800)motor->changeFreq(10);
    if(spentTime>1000)motor->changeFreq(9);
    if(spentTime>1200)motor->changeFreq(7);
    if(spentTime>1400){
      motor->move(0);
      InitActive();;
    }
  }
}


void MODE::DeinitFunction(){
  //
//  led->counter(_InitCounter);
//  _InitCounter++;
  if(_DeinitMode==0){
    motor->move(10);
    if(spentTime>0)motor->changeFreq(8);
    if(spentTime>100)motor->changeFreq(12);
    if(spentTime>200)motor->changeFreq(11);
    if(spentTime>300)motor->changeFreq(10);
    if(spentTime>400)motor->changeFreq(9);
    if(spentTime>500)motor->changeFreq(8);
    if(spentTime>600){
      motor->move(0);
      active=false;
    }
  }

  if(_DeinitMode==1){
    motor->move(10);
    if(spentTime>0)motor->changeFreq(8);
    if(spentTime>100)motor->changeFreq(9);
    if(spentTime>200)motor->changeFreq(10);
    if(spentTime>300)motor->changeFreq(11);
    if(spentTime>400)motor->changeFreq(12);
    if(spentTime>500)motor->changeFreq(8);
    if(spentTime>600){
      motor->move(0);
      active=false;
    }
  }
  if(_DeinitMode==2){
    motor->move(10);
    if(spentTime>0)motor->changeFreq(8);
    if(spentTime>100)motor->changeFreq(12);
    if(spentTime>200)motor->changeFreq(9);
    if(spentTime>300)motor->changeFreq(12);
    if(spentTime>400)motor->changeFreq(9);
    if(spentTime>500)motor->changeFreq(12);
    if(spentTime>600)motor->changeFreq(9);
    if(spentTime>700)motor->changeFreq(12);
    if(spentTime>800)motor->changeFreq(8);
    if(spentTime>900){
      motor->move(0);
      active=false;
    }
  }
  if(_DeinitMode==3){
    motor->move(10);
    if(spentTime>0)motor->changeFreq(8);
    if(spentTime>100)motor->changeFreq(9);
    if(spentTime>200){
      motor->changeFreq(10);
    }
    if(spentTime>300){
      motor->move(0);
    }
    if(spentTime>400){
      motor->move(10);
      motor->changeFreq(11);
    }
    if(spentTime>500)motor->changeFreq(12);
    if(spentTime>600)motor->changeFreq(13);
    if(spentTime>700){
      motor->move(0);
      active=false;
    }
  }
  if(_DeinitMode==4){
      motor->move(10);
    if(spentTime>0){
      motor->changeFreq(12);
    }
    if(spentTime>100)motor->move(0);
    if(spentTime>200){
      motor->move(10);
      motor->changeFreq(10);
    }
    if(spentTime>300){
      motor->changeFreq(11);
    }
    if(spentTime>400){
      motor->changeFreq(8);
    }
    if(spentTime>500){
      motor->move(0);
      active=false;
    }
  }
  if(_DeinitMode==5){
      motor->move(10);
    if(spentTime>0)motor->changeFreq(12);
    if(spentTime>100)motor->changeFreq(8);
    if(spentTime>200)motor->changeFreq(12);
    if(spentTime>300)motor->changeFreq(8);
    if(spentTime>400)motor->changeFreq(12);
    if(spentTime>500)motor->changeFreq(8);
    if(spentTime>600){
      motor->move(0);
      active=false;
    }
  }
  if(_DeinitMode==6){
      motor->move(10);
    if(spentTime>0)motor->changeFreq(12);
    if(spentTime>100)motor->changeFreq(13);
    if(spentTime>200)motor->changeFreq(11);
    if(spentTime>300)motor->changeFreq(10);
    if(spentTime>400)motor->changeFreq(9);
    if(spentTime>500)motor->changeFreq(8);
    if(spentTime>600){
      motor->move(0);
      active=false;
    }
  }
  if(_DeinitMode==7){
    led->clyon();
    if(spentTime>0){
      motor->move(10);
      motor->changeFreq(7);
    }
    if(spentTime>100){
      motor->changeFreq(9);
      //led->flash(50);
    }
    if(spentTime>200){
      motor->changeFreq(8);
      //led->flash(100);
    }
    if(spentTime>300){
      motor->changeFreq(10);
      //led->flash(150);
    }
    if(spentTime>400){
      motor->changeFreq(11);
      //led->flash(200);
    }
    if(spentTime>500){
      motor->changeFreq(12);
      //led->flash(250);
    }
    if(spentTime>600){
      motor->changeFreq(11);
    }
    if(spentTime>800){
      motor->changeFreq(10);
      //led->flash(350);
    }
    if(spentTime>1000){
      motor->changeFreq(9);
    }
    if(spentTime>1200){
      motor->changeFreq(7);
    }
    if(spentTime>1400){
      motor->changeFreq(8);
    }
    if(spentTime>4000){
      motor->move(0);
    }
    if(spentTime>8000){
      active=false;
    }
  }
  if(_DeinitMode==8){
    led->clyon();
    if(spentTime>0){
      motor->move(10);
      motor->changeFreq(10);
    }
    if(spentTime>100){
      motor->changeFreq(9);
      //led->flash(50);
    }
    if(spentTime>200){
      motor->changeFreq(8);
      //led->flash(100);
    }
    if(spentTime>300){
      motor->changeFreq(10);
      //led->flash(150);
    }
    if(spentTime>400){
      motor->changeFreq(11);
      //led->flash(200);
    }
    if(spentTime>500){
      motor->changeFreq(12);
      //led->flash(250);
    }
    if(spentTime>600){
      motor->changeFreq(11);
    }
    if(spentTime>800){
      motor->changeFreq(10);
      //led->flash(350);
    }
    if(spentTime>1000){
      motor->changeFreq(9);
    }
    if(spentTime>1200){
      motor->changeFreq(7);
    }
    if(spentTime>1400){
      motor->changeFreq(8);
    }
    if(spentTime>4000){
      motor->move(0);
    }
    if(spentTime>8000){
      active=false;
    }
  }
}
void MODE::main(){
      
}

